<?php

use Illuminate\Database\Seeder;
use App\Question;
use App\Subject;
class QuestionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $physics = array(
            array('subject_id'=>3,'question'=> 'Terminal potential difference of battery depends on', 'option1' => 'current','option2' => 'temperature','option3' => 'both A and B','option4' => 'resistance of external resistor','correct_ans' =>"d"),
            array('subject_id'=>3,'question'=> 'Density of water in kg m-3 is', 'option1' => 1000,'option2' => 100,'option3' => 10000,'option4' => 4000,'correct_ans' => "a"),
            array('subject_id'=>3,'question'=> 'As object gains speed, its G.P.E (Gravitational Potential Energy', 'option1' => 'increases','option2' => 'remains constant','option3' => 'decreases','option4' => 'varies depending on altitude','correct_ans' => "d"),
            array('subject_id'=>3,'question'=> 'Activity is proportional to number of', 'option1' => 'daughter nuclei','option2' => 'decayed nuclei','option3' => 'decayed nuclei','option4' => 'father nuclei','correct_ans' => "c"),
            array('subject_id'=>3,'question'=> 'A filament lamp is', 'option1' => 'Ohmic','option2' => 'non-Ohmic','option3' => 'low resistive','option4' => 'non glowing','correct_ans' => "b"),
            array('subject_id'=>3,'question'=> 'Intensity of suns radiation is about', 'option1' => '1.0 kW m-2','option2' => '20 kW m-2','option3' => '5 kW m-2','option4' => '8 kW m-2','correct_ans' => "a"),
            array('subject_id'=>3,'question'=> 'Phenomena in which a charged body attract uncharged body is called', 'option1' => 'electrostatic induction','option2' => 'electric current','option3' => 'charge movement','option4' => 'magnetic induction','correct_ans' => "a"),
            array('subject_id'=>3,'question'=> 'Semiconductors have electron number density of order', 'option1' => '1024 m-3','option2' => '1020 m-3','option3' => '1012 m-3','option4' => '1023 m-3','correct_ans' => "d"),
            array('subject_id'=>3,'question'=> 'An electron is travelling at right angles to a uniform magnetic field of flux density 1.2 mT with a speed of 8 × 106 m s-1, radius of circular path followed by electron is', 'option1' => '3.8 cm','option2' => '3.7 cm','option3' => '3.6 cm','option4' => '3.5 cm','correct_ans' => "a"),
            array('subject_id'=>3,'question'=> 'High speed electrons have wavelength of order', 'option1' => '10-15 m','option2' => '10-14 m','option3' => '10-16 m','option4' => '10-17 m','correct_ans' => "a"),
            array('subject_id'=>3,'question'=> 'Strength of magnetic field is known as', 'option1' => 'flux','option2' => 'density','option3' => 'magnetic strength','option4' => 'magnetic flux density','correct_ans' => "d"),
            array('subject_id'=>3,'question'=> 'Only force acting on a bouncing ball is', 'option1' => 'gravity','option2' => 'weight of ball','option3' => 'friction','option4' => 'a and b both','correct_ans' => "a"),
            array('subject_id'=>3,'question'=> 'Gradual decrease in x-ray beam intensity as it passes through material is called', 'option1' => 'attenuation','option2' => 'decay','option3' => 'radioactivity','option4' => 'imaging','correct_ans' => "a"),
            array('subject_id'=>3,'question'=> 'A straight line symbol shows the', 'option1' => 'fuse','option2' => 'diode','option3' => 'connecting lead','option4' => 'switch','correct_ans' => "c"),
            array('subject_id'=>3,'question'=> 'Visible light has wavelength of', 'option1' => '5 × 10-7 m','option2' => '3 × 108 m','option3' => '6 × 10³ m','option4' => '4 × 104 m','correct_ans' => "a"),
            array('subject_id'=>3,'question'=> 'Force acting on two point masses is directly proportional to', 'option1' => 'sum of masses','option2' => 'difference of masses','option3' => 'distance between masses','option4' => 'product of masses','correct_ans' => "d"),
            array('subject_id'=>3,'question'=> 'Maximum displacement from equilibrium position is', 'option1' => 'frequency','option2' => 'amplitude','option3' => 'wavelength','option4' => 'period','correct_ans' => "b"),
            array('subject_id'=>3,'question'=> 'Attenuation coefficient of bone is 600 m-1 for x-rays of energy 20 keV and intensity of beam of x-rays is 20 Wm-2, then intensity of beam after passing through a bone of 4mm is', 'option1' => '3 Wm-2','option2' => '2.5 Wm-2','option3' => '2.0 Wm-2','option4' => '1.8 Wm-2','correct_ans' => "d"),
            array('subject_id'=>3,'question'=> 'Contact force always acts at parallel to the surface producing it', 'option1' => 'acute angles to the surface producing it','option2' => 'right angles to the surface producing it','option3' => 'obtuse angle to the surface producing it','option4' => 'obtuse angle to the surface producing it','correct_ans' => "b"),
            array('subject_id'=>3,'question'=> 'Unit of luminous intensity is', 'option1' => 'm','option2' => 'kg','option3' => 'cd','option4' => 'mol','correct_ans' => "c"),
            array('subject_id'=>3,'question'=> ' As compared to sound waves frequency of radio waves is', 'option1' => 'lower','option2' => 'higher','option3' => 'equal','option4' => 'may be higher or lower','correct_ans' => "b"),
            array('subject_id'=>3,'question'=> 'Decrease in strength of signal is known as', 'option1' => 'tuning','option2' => 'modulation','option3' => 'attenuation','option4' => 'amplification','correct_ans' => "c"),
            array('subject_id'=>3,'question'=> 'E.M.F can be induced in a circuit by', 'option1' => 'changing magnetic flux density','option2' => 'changing area of circuit','option3' => 'changing the angle','option4' => 'all of above','correct_ans' => "d"),
            array('subject_id'=>3,'question'=> 'Resistivity of lead is', 'option1' => '22.5 × 10-8 Ω m','option2' => '20.8 × 10-8 Ω m','option3' => '10 Ω m','option4' => '5 Ω m','correct_ans' => "b"),
            array('subject_id'=>3,'question'=> 'If a secondary coil has 40 turns, and, a primary coil with 20 turns is charged with 50 V of potential difference, then potential difference in secondary coil would be', 'option1' => '50 V in secondary coil','option2' => '100 V in secondary coil','option3' => '60 V in secondary coil','option4' => '25 V in secondary coil','correct_ans' => "d"),
            array('subject_id'=>3,'question'=> 'Effect of diffraction is greatest if waves pass through a gap with width equal to', 'option1' => 'frequency','option2' => 'wavelength','option3' => 'amplitude','option4' => 'wavefront','correct_ans' => "b"),
            array('subject_id'=>3,'question'=> 'In order to find internal structure of nucleus, electrons should be accelerated by voltages up to', 'option1' => '105 V','option2' => '107 V','option3' => '109 V','option4' => '1011 V','correct_ans' => "c"),
            array('subject_id'=>3,'question'=> 'Particles involved in movement within material are', 'option1' => 'protons','option2' => 'electrons','option3' => 'neutrons','option4' => 'positrons','correct_ans' => "c"),
            array('subject_id'=>3,'question'=> ' As compared to sound waves frequency of radio waves is', 'option1' => 'lower','option2' => 'higher','option3' => 'equal','option4' => 'may be higher or lower','correct_ans' => "b"),
            array('subject_id'=>3,'question'=> 'Decrease in strength of signal is known as', 'option1' => 'tuning','option2' => 'modulation','option3' => 'attenuation','option4' => 'amplification','correct_ans' => "c"),
            array('subject_id'=>3,'question'=> 'E.M.F can be induced in a circuit by', 'option1' => 'changing magnetic flux density','option2' => 'changing area of circuit','option3' => 'changing the angle','option4' => 'all of above','correct_ans' => "d"),
            array('subject_id'=>3,'question'=> 'Systematic errors occur due to', 'option1' => 'overuse of instruments','option2' => 'careless usage of instruments','option3' => 'both A and B','option4' => 'human sight','correct_ans' => "c"),
            array('subject_id'=>3,'question'=> 'Speed of Earth when a rock of mass 60 kg falling towards Earth with speed of 20 m s-1 is', 'option1' => '2.4 × 10-22 m s-1','option2' => '3.5 × 10-33 m s-1','option3' => '−2.0 × 10-22 m s-1','option4' => '−3 × 1034 m s-1','correct_ans' => "c"),
            array('subject_id'=>3,'question'=> ' Normal force acting per unit cross sectional area is called', 'option1' => 'weight','option2' => 'pressure','option3' => 'volume','option4' => 'friction','correct_ans' => "b"),
            array('subject_id'=>3,'question'=> ' Accelerometer detects the', 'option1' => 'small acceleration','option2' => 'large acceleration','option3' => 'small deceleration','option4' => 'large acceleration and deceleration','correct_ans' => "d"),
            array('subject_id'=>3,'question'=> 'Combinations of base units are', 'option1' => 'simple units','option2' => 'derived units','option3' => 'scalars','option4' => 'vectors','correct_ans' => "b"),
            array('subject_id'=>3,'question'=> 'If plates of capacitor are oppositely charged then total charge is equal to', 'option1' => 'negative','option2' => 'positive','option3' => 'zero','option4' => 'infinite','correct_ans' => "c"),
            array('subject_id'=>3,'question'=> 'LED starts to conduct when voltage is about', 'option1' => '1 V','option2' => '4 V','option3' => '3 V','option4' => '2 V','correct_ans' => "c"),
            array('subject_id'=>3,'question'=> 'LED starts to conduct when voltage is about', 'option1' => '1 V','option2' => '4 V','option3' => '3 V','option4' => '2 V','correct_ans' => "d"),
            array('subject_id'=>3,'question'=> ' For non-inverting amplifier input and output is', 'option1' => 'out of phase','option2' => 'in phase','option3' => 'have phase difference of 180°','option4' => 'have phase difference of 90°','correct_ans' => "b"),
            array('subject_id'=>3,'question'=> ' If gradient of a graph is negative, then acceleration is', 'option1' => 'positive','option2' => 'negative','option3' => 'zero°','option4' => '1°','correct_ans' => "b"),
            array('subject_id'=>3,'question'=> 'Ratio of tensile to strain is', 'option1' => "Young's modulus",'option2' => 'stress','option3' => 'stiffness','option4' => 'tensile force','correct_ans' => "a"),
            array('subject_id'=>3,'question'=> ' Energy given to nucleus to dismantle it increases the', 'option1' => 'kinetic energy of individual nucleons','option2' => 'mechanical energy of individual nucleons','option3' => 'potential energy of individual nucleons','option4' => 'chemical energy of individual nucleons','correct_ans' => "c"),
            array('subject_id'=>3,'question'=> 'Tensile strain is equal to', 'option1' => 'Force per unit area','option2' => 'Force per unit volume','option3' => 'Extension per unit length','option4' => 'Force per unit length','correct_ans' => "c"),
            array('subject_id'=>3,'question'=> 'If energy loss is zero then decrease in G.P.E is equal to', 'option1' => 'decreases in kinetic energy','option2' => 'gain in kinetic energy','option3' => 'constant kinetic energy','option4' => 'zero kinetic energy','correct_ans' => "b"),
            array('subject_id'=>3,'question'=> 'In case of filament lamp at higher voltages, resistance of lamp', 'option1' => 'decreases','option2' => 'increases','option3' => 'remains constant','option4' => 'varies depending on the filament','correct_ans' => "b"),
            array('subject_id'=>3,'question'=> 'Supply of energy depends upon', 'option1' => 'mass of material','option2' => 'the change in temperature','option3' => 'the material itself','option4' => 'all of above','correct_ans' => "d"),
            array('subject_id'=>3,'question'=> ' If frequency of modulated wave is less than frequency of carrier wave, then input signal is', 'option1' => 'negative','option2' => 'positive','option3' => 'zero','option4' => 'all of above','correct_ans' => "a"),
            array('subject_id'=>3,'question'=> 'Average power of all activities of our body is', 'option1' => '111 W','option2' => '113 W','option3' => '116 W','option4' => '120 W','correct_ans' => "c"),
            array('subject_id'=>3,'question'=> 'Kinetic friction is always', 'option1' => 'lesser than static friction','option2' => 'greater than static friction','option3' => 'equal to static friction','option4' => 'equal to contact force','correct_ans' => "a"),
            array('subject_id'=>3,'question'=> 'Gravitational potential is always', 'option1' => 'positive','option2' => 'negative','option3' => 'zero','option4' => 'infinity','correct_ans' => "b"),
            array('subject_id'=>3,'question'=> 'Displacement-time graph depicting an oscillatory motion is', 'option1' => 'cos curve','option2' => 'sine curve','option3' => 'sine curve','option4' => 'straight line','correct_ans' => "c"),
            array('subject_id'=>3,'question'=> 'Rate of flow of electric charge is', 'option1' => 'electric current','option2' => 'conventional current only','option3' => 'electronic current only','option4' => 'potential difference','correct_ans' => "a"),
         );     
         Question::insert($physics);   
         // End of Physics Question
         $math = array(
            array('subject_id'=>1,'question'=> 'Simplify 15ax2 ⁄ 5x', 'option1' => '3ax2','option2' => '3ax','option3' => '5ax2','option4' => '5ax','correct_ans' =>"b"),
            array('subject_id'=>1,'question'=> 'Simplify 5⁄2 ÷ 1⁄x', 'option1' => '5x ⁄ 2','option2' => '5 ⁄ 2x','option3' => '2 ⁄ 5x','option4' => '2x ⁄ 5','correct_ans' => "a"),
            array('subject_id'=>1,'question'=> 'Simplify a(c - b) - b(a - c)', 'option1' => 'ac - 2ab - bc','option2' => 'ac - 2ab + bc','option3' => 'ac + 2ab + bc','option4' => 'ac + bc','correct_ans' => "b"),
            array('subject_id'=>1,'question'=> ' Coefficient of x2 in 4x3 + 3x2 - x + 1 is:', 'option1' => '1','option2' => '-1','option3' => '3','option4' => '2','correct_ans' => "c"),
            array('subject_id'=>1,'question'=> 'Expand and simplfy (x - 5)(x + 4)', 'option1' => 'x2 + 9x - 20','option2' => 'x2 - x - 9','option3' => 'x2 - x - 1','option4' => 'x2 - x - 20','correct_ans' => "d"),
            array('subject_id'=>1,'question'=> 'Expand and simplfy (x - y)(x + y)', 'option1' => 'x2 - 2xy + y2','option2' => 'x2 + 2xy + y2','option3' => 'x2 - y2','option4' => 'x2 + y2','correct_ans' => "c"),
            array('subject_id'=>1,'question'=> '(a - b)2 =', 'option1' => 'a2 - 2ab + b2','option2' => 'a2 + 2ab + b2','option3' => 'a2 - b2','option4' => 'a2 + b2','correct_ans' => "a"),
            array('subject_id'=>1,'question'=> 'Factorise x2 + x - 72', 'option1' => '(x - ?72)(x + ?72)','option2' => '(x - ?72)2','option3' => '(x - 8)(x + 9)','option4' => '(x + 8)(x - 9)','correct_ans' => "c"),
            array('subject_id'=>1,'question'=> 'Factorise -20x2 - 9x + 20', 'option1' => '(5 + 4x)(4 - 5x)','option2' => '(5 - 4x)(4 - 5x)','option3' => '(5 - 4x)(4 + 5x)','option4' => '(5 + 4x)(4 + 5x)','correct_ans' => "a"),
            array('subject_id'=>1,'question'=> 'Expand and simplify (x + y)3', 'option1' => 'x3 + 3xy(x - y) + y3','option2' => 'x3 + 3xy(x + y) + y3','option3' => 'x3 + y3','option4' => 'x3 - y3','correct_ans' => "b"),
            array('subject_id'=>1,'question'=> ' Simplify (x - 9)(x + 10) ⁄ (x2 - 81)', 'option1' => '(x2 + x - 90) ⁄ (x2 - 81)','option2' => '(x + 10) ⁄ (x - 9)','option3' => '(x + 10) ⁄ (x + 9)','option4' => 'None of the above','correct_ans' => "c"),
            array('subject_id'=>1,'question'=> ' Simplify (3x ⁄ 2y)(x ⁄ 3y)', 'option1' => 'x ⁄ 2y','option2' => '(3x2) ⁄ (2y2)','option3' => 'x2 ⁄ (6y2)','option4' => 'x2 ⁄ (2y2)','correct_ans' => "d"),
            array('subject_id'=>1,'question'=> 'Simplify (1 ⁄ (x2 - 1)) ÷ (1 ⁄ (x + 1))', 'option1' => '1 ⁄ (x - 1)','option2' => '1 ⁄ (x + 1)','option3' => '1 ⁄ (x2 - 1)','option4' => 'None of the above','correct_ans' => "a"),
            array('subject_id'=>1,'question'=> ' Simplify (1 ⁄ s) - (1 ⁄ t)', 'option1' => '(s - t) ⁄ st','option2' => '(t - s) ⁄ st','option3' => '0','option4' => '1 ⁄ (s - t)','correct_ans' => "b"),
            array('subject_id'=>1,'question'=> 'Simplify (2 ⁄ tanA) + (4 ⁄ tanB)', 'option1' => '(2tanB + 4tanA) ⁄ tanAtanB','option2' => '(2tanA + 4tanB) ⁄ tanAtanB','option3' => '6 ⁄ (tanA + tanB)','option4' => 'None of the above','correct_ans' => "a"),
            array('subject_id'=>1,'question'=> '1 ⁄ (x2 - 1) can be expressed as (A ⁄ (x+1)) + (B ⁄ (x-1)), which of following pairs of values of A and B is correct?', 'option1' => 'A = 1, B = -1','option2' => 'A = 1⁄2, B = -1⁄2','option3' => 'A = -1⁄2, B = 1⁄2','option4' => 'A = 1, B = 0','correct_ans' => "b"),
            array('subject_id'=>1,'question'=> 'Express ?20 in terms of simplest possible surd.', 'option1' => '10','option2' => '5?2','option3' => '4?5','option4' => '2?5','correct_ans' => "d"),
            array('subject_id'=>1,'question'=> 'Express ?500 in terms of simplest possible surd.', 'option1' => '10?50','option2' => '50?10','option3' => '10?5','option4' => '5?10','correct_ans' => "c"),
            array('subject_id'=>1,'question'=> ' Expand and simplify (3 + 2?5)(6 + 4?5)
', 'option1' => '58 + 24?5','option2' => '58 + 12?5','option3' => '58 + 24?10','option4' => '18 + 32?5','correct_ans' => "a"),
            array('subject_id'=>1,'question'=> 'Rationalise denominator of 1 ⁄ (3?5 - 3?2), simplify where possible', 'option1' => '(3?5 - 3?2) ⁄ (63 - 18?10)','option2' => '(3?5 + 3?2) ⁄ 27','option3' => '(3?5 + 3?2) ⁄ (63 - 18?10)','option4' => '(3?5 - 3?2) ⁄ 27','correct_ans' => "b"),
            array('subject_id'=>1,'question'=> ' Simplify (a^(-1 ⁄ 3) × a^(1 ⁄ 3)) ⁄ a^(-1 ⁄ 2)', 'option1' => 'a^(-7 ⁄ 18)','option2' => 'a^(-1 ⁄ 2)','option3' => 'a^(1 ⁄ 2)','option4' => 'None of the above','correct_ans' => "c"),
            array('subject_id'=>1,'question'=> 'Evaluate (1 ⁄ 64)^(-1⁄3)4^-1', 'option1' => 'tuning','option2' => '4','option3' => '2^-1','option4' => '2','correct_ans' => "b"),
            array('subject_id'=>1,'question'=> 'Logarithm to base 10 of 1000 is:', 'option1' => '1','option2' => '2','option3' => '3','option4' => '4','correct_ans' => "c"),
            array('subject_id'=>1,'question'=> "Index form of 'logarithm to base x of y is z' is:", 'option1' => 'x^z = y','option2' => 'x^y = z','option3' => 'y^z = x','option4' => 'z^y = x','correct_ans' => "a"),
            array('subject_id'=>1,'question'=> "In logarithmic form of '2&sup6; = 64':", 'option1' => 'base = 6, log = 2, number = 64','option2' => 'base = 2, log = 6, number = 64','option3' => 'base = 2, log = 64, number = 6','option4' => 'base = 64, log = 2, number = 6','correct_ans' => "b"),
            array('subject_id'=>1,'question'=> 'Logarithm to base 1⁄2 of 16 is:', 'option1' => '4','option2' => '5','option3' => '-5','option4' => '-4','correct_ans' => "d"),
            array('subject_id'=>1,'question'=> "Logarithm of 'x' to power 'y' is equal to:", 'option1' => 'y × (logarithm of x)','option2' => 'x × (logarithm of y)','option3' => "(logarithm of 'x') × (logarithm of 'y')",'option4' => 'None of the above','correct_ans' => "a"),
            array('subject_id'=>1,'question'=> 'Solve equation 4x2 + 36x + 81', 'option1' => 'x = 9⁄2, x = 9⁄2','option2' => 'x = -9⁄2, x = 9⁄2','option3' => 'x = -9⁄2, x = -9⁄2','option4' => 'None of the above','correct_ans' => "c"),
            array('subject_id'=>1,'question'=> ' Solve equation x2 + 6x - 7 = 0', 'option1' => 'x = -6, x = -1','option2' => 'x = -6, x = 1','option3' => 'x = 6, x = -1','option4' => 'x = 6, x = 1','correct_ans' => "d"),
            array('subject_id'=>1,'question'=> ' Solve equation x2 + 3x', 'option1' => 'x = -3','option2' => 'x = 0, x = -3','option3' => 'x = 3','option4' => 'x = 0, x = 3','correct_ans' => "b"),
            array('subject_id'=>1,'question'=> 'Find by using formula roots for following equation: ax2 + bx + c', 'option1' => '(-b±?(b2 - 4ac)) ⁄ 2a','option2' => '(b ± ?(b2 - 4ac)) ⁄ 2a','option3' => '(-b ± ?(b2 + 4ac)) ⁄ 2a','option4' => '(-b ± ?(b2 - 4c)) ⁄ 2a','correct_ans' => "a"),
            array('subject_id'=>1,'question'=> 'Solve equations: x + 2y = 13, x + y + z = 12, 2y + z = 11', 'option1' => 'x = 3, y = 4, z = 5','option2' => 'x = 5, y = 4, z = 3','option3' => 'x = 4, y = 5, z = 3','option4' => 'x = 3, y = 5, z = 4','correct_ans' => "b"),
            array('subject_id'=>1,'question'=> 'Value of b2 - 4ac determines nature of roots, for real and different roots, b2 - 4ac is:', 'option1' => 'lesser than 0','option2' => 'equal to 0','option3' => 'greater than 0','option4' => 'None of the above','correct_ans' => "c"),
            array('subject_id'=>1,'question'=> '  Value of b2 - 4ac determines nature of roots, for real and equal roots, b2 - 4ac is:', 'option1' => 'lesser than 0','option2' => 'equal to 0','option3' => 'greater than 0','option4' => 'None of the above','correct_ans' => "b"),
            array('subject_id'=>1,'question'=> 'Sum of roots of a quadratic equation is equal to:', 'option1' => '-b ⁄ 2a','option2' => '-2b ⁄ a','option3' => '-b ⁄ a','option4' => 'b ⁄ a','correct_ans' => "c"),
            array('subject_id'=>1,'question'=> 'Length of line joining two points (x1, y1) and (x2, y2) is:', 'option1' => '(x2 - x1) + (y2 - y1)','option2' => '?((x2 - x1) + (y2 - y1))','option3' => '?((x2 - x1)2 + (y2 - y1)2)','option4' => '(y2 - y1) ⁄ (x2 - x1)','correct_ans' => "c"),
            array('subject_id'=>1,'question'=> 'Coordinates of midpoint of line joining two points (x1, y1) and (x2, y2) are:', 'option1' => '((x2 - x1) ⁄ 2, (y2 - y1) ⁄ 2)','option2' => '((x2 + x1) ⁄ 2, (y2 + y1) ⁄ 2)','option3' => '((x2 - x1), (y2 - y1))','option4' => '((x2 + x1), (y2 + y1))','correct_ans' => "b"),
            array('subject_id'=>1,'question'=> ' Coordinates of midpoint of line joining two points (1, 2) and (4, 8) are:', 'option1' => '(2.5, 10)','option2' => '(5, 5)','option3' => '(5, 10)','option4' => '(2.5, 5)','correct_ans' => "d"),
            array('subject_id'=>1,'question'=> 'Length of line joining two points (1, 2) and (4, 8) is:', 'option1' => '3','option2' => '9','option3' => '?45','option4' => '45','correct_ans' => "c"),
            array('subject_id'=>1,'question'=> 'Coordinates of midpoint of line joining two points (16, 4) and (36, 6) are:', 'option1' => '(26, 5)','option2' => '(5, 26)','option3' => '(10, 1)°','option4' => '(1, 10)°','correct_ans' => "a"),
            array('subject_id'=>1,'question'=> ' Length of line joining two points (16, 4) and (36, 6) is:', 'option1' => '22','option2' => '?22','option3' => '404','option4' => '?404','correct_ans' => "d"),
            array('subject_id'=>1,'question'=> 'Consider a line passing through (1, 2) and (4, 8), gradient of this line is equal to:', 'option1' => "1 ⁄ 2",'option2' => '-1 ⁄ 2','option3' => '2','option4' => '-2','correct_ans' => "c"),
            array('subject_id'=>1,'question'=> 'Consider a line passing through (16, 4) and (36, 6), gradient of this line is equal to:', 'option1' => '-0.1','option2' => '0.1','option3' => '-10','option4' => '10','correct_ans' => "b"),
            array('subject_id'=>1,'question'=> 'A father of three daughters bought 6 dolls at $10 each and a few stationary items costing about $5 each. Overall, he spent $200. How many stationary items did he purchase?', 'option1' => '20 items','option2' => '25 items','option3' => '28 items','option4' => '30 items','correct_ans' => "c"),
            array('subject_id'=>1,'question'=> 'Sum of numbers from 1 to 100 i.e. (1+2+3+4+5+6', 'option1' => '505','option2' => '5050','option3' => '550','option4' => '5500','correct_ans' => "b"),
            array('subject_id'=>1,'question'=> '(0.001)2 ÷ 1000 is equal to:', 'option1' => '1000','option2' => '0.001','option3' => '0.00000001','option4' => '0.000000001','correct_ans' => "d"),
            array('subject_id'=>1,'question'=> 'Arrange following fractions in ascending order: (2 ⁄ 7), (4 ⁄ 9), (1 ⁄ 5), (3 ⁄ 8)', 'option1' => '(1 ⁄ 5), (2 ⁄ 7), (3 ⁄ 8), (4 ⁄ 9)','option2' => '(1 ⁄ 5), (4 ⁄ 9), (2 ⁄ 7), (3 ⁄ 8)','option3' => '(1 ⁄ 5), (4 ⁄ 9), (3 ⁄ 8), (2 ⁄ 7)','option4' => '(4 ⁄ 9), (3 ⁄ 8), (2 ⁄ 7), (1 ⁄ 5)','correct_ans' => "a"),
            array('subject_id'=>1,'question'=> 'Arrange following fractions in descending order: (2 ⁄ 7), (4 ⁄ 9), (1 ⁄ 5), (3 ⁄ 8)', 'option1' => '(1 ⁄ 5), (2 ⁄ 7), (3 ⁄ 8), (4 ⁄ 9)','option2' => '(1 ⁄ 5), (4 ⁄ 9), (2 ⁄ 7), (3 ⁄ 8)','option3' => '(1 ⁄ 5), (4 ⁄ 9), (3 ⁄ 8), (2 ⁄ 7)','option4' => '(4 ⁄ 9), (3 ⁄ 8), (2 ⁄ 7), (1 ⁄ 5)','correct_ans' => "d"),
            array('subject_id'=>1,'question'=> 'Mid-way fraction of (5 ⁄ 6) and (8 ⁄ 15) is:', 'option1' => '41 ⁄ 30','option2' => '41 ⁄ 60','option3' => '13 ⁄ 21','option4' => 'None of the above','correct_ans' => "b"),
            array('subject_id'=>1,'question'=> 'A tank of water contains 250 liters of water, if 10 milliliters of water is removed from it every second of an hour, how much water would be left in it after 5 hours. (1 liter = 1000 ml)
', 'option1' => '60 liters','option2' => '65 liters','option3' => '70 liters','option4' => '180 liters','correct_ans' => "c"),
            array('subject_id'=>1,'question'=> ' Among 1, 2, 3, 4, 5, 6, 12, 13, 14, 15, 16, 17, prime numbers include:', 'option1' => '1, 2, 3, 5, 12, 13, 15, 17','option2' => '1, 2, 3, 5, 13, 15, 17','option3' => '1, 2, 3, 5, 13, 17','option4' => '2, 3, 5, 13, 17','correct_ans' => "d"),
            array('subject_id'=>1,'question'=> 'Among 0.5, 1, √(4), π, and (5 ⁄ 8), irrational numbers are:', 'option1' => '0.5, √(4) and π','option2' => '√(4) and π','option3' => 'π only','option4' => 'None of them is an irrational number','correct_ans' => "c"),
            array('subject_id'=>1,'question'=> 'If 0 is first time, nth term of sequence 0, 4, 8, 12, 16,', 'option1' => '4 × n','option2' => '4 × (n + 1)','option3' => '4 × (n - 1)','option4' => 'None of the above','correct_ans' => "c"),
         );     
         Question::insert($math);   
    }
}
